---

- hosts: zookeeper
  roles:
    - zookeeper_start

- hosts: hadoop-hdfs-journalnode
  roles:
    - hadoop-hdfs-journalnode_start

- hosts: hadoop-hdfs-namenode-active
  roles:
    - hadoop-hdfs-namenode_start

- hosts: hadoop-hdfs-namenode-standby
  roles:
    - hadoop-hdfs-namenode_start

- hosts: hadoop-hdfs-datanode
  roles:
    - hadoop-hdfs-datanode_start

# TODO: wait until leave safemode

- hosts: hadoop-yarn-resourcemanager-active
  roles:
    - hadoop-yarn-resourcemanager_start

- hosts: hadoop-yarn-resourcemanager-standby
  roles:
    - hadoop-yarn-resourcemanager_start

- hosts: hadoop-yarn-nodemanager
  roles:
    - hadoop-yarn-nodemanager_start

- hosts: hadoop-mapreduce-historyserver
  roles:
    - hadoop-mapreduce-historyserver_start
