

- name: stop primary namenode zkfc
  become: yes
  systemd:
     name: hadoop-hdfs-zkfc
     state: stopped
     daemon_reload: yes
     enabled: no


- name: stop primary namenode
  become: yes
  systemd:
     name: hadoop-hdfs-namenode
     state: stopped
     daemon_reload: yes
     enabled: no
